---
builds:
  - id: mcpx-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    dir: .
    main: main.go
    binary: mcpx-cli
    flags:
      - -trimpath
    ldflags: -s -w -X main.version={{.Tag}}

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
