---
name: "release"

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.AI_MCPX_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.AI_MCPX_TOKEN }}
        timeout-minutes: 5
      - name: Create release
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.AI_MCPX_TOKEN }}
        timeout-minutes: 20
